name: Build Apptainer in Ubuntu-22.04

on:
  schedule:
    - cron:  '0 2 ? * SUN'
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        
      - name: Docker install
        run: wget https://raw.githubusercontent.com/sigmaresearch100/docker-ubuntu-22.04/main/src/docker.sh | sudo bash
            
      - name: Apptainer install
        run: sudo bash ${PWD}/src/apptainer.sh
